### ISSUE TITLE
Problemas con thunder client y el añadir una cancion 

### ISSUE THREAD

**Issue by JoelFEscobar** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct12-music-api-grupo-m#3]
Buenas noches, @esegredo

He estado implementando el funcionamiento de los distintos routers que crean los puntos de acceso a la API. Artista y todos sus metodos funcionan correctamente tal y como he estado comprobando a través de thunderClient. Sin embargo, al realizar una peticion post sobre las canciones (esquema song). Resulta que me salta un status 404 not found. Sin embargo, en mi codigo realizo el mismo planteamiento que si quiero añadir un artista, especificamente la funcion para añadir un router es:

```TypeScript
songRouter.post('/song', async (req, res) => {
  const song = new songModel(req.body);
  try {
    await song.save();
    res.status(201).send(song);
  } catch (error) {
    res.status(400).send(error);
  }
});
```
En thunderClient para realizar la peticion, selecciono el método post e introduzco la URL: `http://localhost:3000/song` correspondiente al puerto donde esta escuchando el servidor. Luego introduzco por ejemplo el siguiente cuerpo que va a ser el objeto que quiero introducir:

 ```JSON
{
    "name": "Bellyache",
    "author": [{
        "name": "Billie Eilish",
        "genres": ["POP", "RAP"] 
    }],
    "duration": 2.30,
    "genres": ["POP"],
    "single": true,
    "reproduction": 3903,
    "listeners": 400
}
```

Como error salta un status 404 not found y en el cuerpo de la peticion se visualiza `    <pre>Cannot POST /song</pre>` 

No sabemos a que puede ser debido puesto, que aparentemente esta bien definido el nuevo objeto.

Un saludo y gracias de antemano.

**Comment by esegredo** [comment]
¿Han registrado el router en la aplicación, haciendo uso de app.use?

Es raro que conteste con un 404 cuando en el manejador que muestras no estableces el código de la respuesta a ese valor.

Saludos.

**Comment by JoelFEscobar** [comment]
Ya lo solucionamos, fue fallo de una constante no definida y no permitía
acceso a la base de datos por lo que respondia con el 404
